[package]
name = "dfint_hook"
version = "0.1.3"
edition = "2021"

[lib]
name = "dfint_hook"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
macro = { path = "src/macro" }
raw = { path = "src/raw" }

retour = { version = "0.3.1", features = ["static-detour"] }
log = "0.4.27"
simple-logging = "2.0.2"
regex = "1.11.1"
backtrace = "0.3.74"
serde = { version = "1.0.219", features = ["derive"] }
static_init = "1.0.3"
anyhow = "1.0.97"
device_query = "3.0.1"
sdl2 = "0.37.0"
fontdue = "0.9.3"
bitflags = "2.9.0"
csv = "1.3.1"
indexmap = "2.8.0"

[target.'cfg(target_os = "windows")'.dependencies]
exe = "0.5.6"
winapi = { version = "0.3.9", features = [
  "minwindef",
  "winnt",
  "libloaderapi",
  "windef",
  "winuser",
] }

[target.'cfg(target_os = "linux")'.dependencies]
checksum = "0.2.1"
